Update patch set 11
Patch Set 11:

I run "cargo build" in frameworks/base/libs/binder/rust with this patch,
and got the following error:

error: failed to run custom build command for `binder v0.1.0 (.../frameworks/base/libs/binder/rust)`

Caused by:
  process didn't exit successfully: `.../frameworks/base/libs/binder/rust/target/debug/build/binder-4204568d6eb
dc8f9/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=binder
cargo:rerun-if-changed=src/sys/BinderBindings.h
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
src/sys/BinderBindings.h:17:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
src/sys/BinderBindings.h:24:10: fatal error: 'binder/IPCThreadState.h' file not found
src/sys/BinderBindings.h:17:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
src/sys/BinderBindings.h:24:10: fatal error: 'binder/IPCThreadState.h' file not found, err: true
thread 'main' panicked at 'Bindgen failed to generate bindings for libbinder: ()', build.rs:9:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Patch-set: 11