[StorageStats]:Array out of bounds issue fixed
StorageStatService has the problem that the array is out of bounds and is not an array null pointer.
From the following trace, there is a high probability that the problem of thread synchronization occurs,
so the lock is used for protection
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.android.server.usage.StorageStatsService.queryExternalStatsForUser(StorageStatsService.java:401)
at android.app.usage.StorageStatsManager.queryExternalStatsForUser(StorageStatsManager.java:325)
at android.app.usage.StorageStatsManager.queryExternalStatsForUser(StorageStatsManager.java:339)
at com.android.server.storage.FileCollector.getMeasurementResult(FileCollector.java:172)
at com.android.server.storage.DiskStatsLoggingService$LogRunnable.run(DiskStatsLoggingService.java:163)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

Test: Manual

Signed-off-by: shaozhongqi <shaozhongqi@xiaomi.com>
Change-Id: I004f347ab96ef0334bd8e218b62f2b5be5a478f4