libbinder: show 'GUARDED_BY' behavior
This works, but when GUARDED_BY is used in a header, it fails with this
error:

FAILED:
out/soong/.intermediates/frameworks/native/libs/binder/libbinder/linux_glibc_x86_64_static/obj/frameworks/native/libs/binder/LazyServiceRegistrar.o
PWD=/proc/self/cwd
prebuilts/clang/host/linux-x86/clang-r407598b/bin/clang++ -c
-Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic
-Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow
-Wno-final-dtor-non-final-class -Wno-psabi  -Wa,--noexecstack -fPI
C -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector
-D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS
--gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8
--sysroot
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot
-fstack-protector-strong -m64
-DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self
-Wpointer-arith -Wunreachable-code-loop-increment -no-canonical-prefixes
-DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g
-fdebug-info-for-profiling -fno-strict-aliasing -Werror=date-time
-Werror=pragma-pack -Werro
r=pragma-pack-suspicious-include -Werror=string-plus-int
-Werror=unreachable-code-loop-increment
-fdebug-prefix-map=/proc/self/cwd=
-D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon
-Werror=int-conversion -fexperimental-new-pass-manager
-Wno-reserved-id-macro -Wno-unused-
command-line-argument -fcolor-diagnostics -Wno-sign-compare
-Wno-defaulted-function-deleted -Wno-inconsistent-missing-override
-Wno-c99-designator -Wunguarded-availability
-D__ANDROID_UNGUARDED_AVAILABILITY__ -ftrivial-auto-var-init=zero
-enable-trivial-auto-var-init-zero-knowing-i
t-will-be-removed-from-clang   -target x86_64-linux-gnu
-Bprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/bin
-DANDROID_STRICT -fPIC -Wsign-promo -Wimplicit-fallthrough
-D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next
-Ibionic/libc/kernel/andr
oid/uapi -Ibionic/libc/kernel/uapi -Iframeworks/native/libs/binder
-Iout/soong/.intermediates/frameworks/native/libs/binder/libbinder/linux_glibc_x86_64_static/gen/aidl
-Iframeworks/native/libs/binder/include -Isystem/libbase/include
-Isystem/core/libcutils/include -Isystem/core/li
butils/include -Isystem/unwinding/libbacktrace/include
-Isystem/logging/liblog/include -Isystem/core/libsystem/include
-Isystem/core/libprocessgroup/include -Iexternal/libcxx/include
-Iexternal/libcxxabi/include -Wall -Wextra -Wextra-semi -Werror
-Wthread-safety -Wzero-as-null-poin
ter-constant -DANDROID_BASE_UNIQUE_FD_DISABLE_IMPLICIT_CONVERSION
-fsanitize=integer -fno-sanitize=vptr,function
-fsanitize-minimal-runtime -fno-sanitize-trap=integer,undefined
-fno-sanitize-recover=integer,undefined -fno-sanitize-recover=all
-fno-sanitize=implicit-integer-sign-cha
nge -fno-sanitize=unsigned-shift-base -std=gnu++17 -nostdinc++
-Isystem/core/include -Isystem/logging/liblog/include
-Isystem/media/audio/include -Ihardware/libhardware/include
-Ihardware/libhardware_legacy/include -Ihardware/ril/include
-Iframeworks/native/include -Iframeworks/nat
ive/opengl/include -Iframeworks/av/include  -Werror=bool-operation
-Werror=implicit-int-float-conversion -Werror=int-in-bool-context
-Werror=int-to-pointer-cast -Werror=pointer-to-int-cast
-Werror=string-compare -Werror=xor-used-as-pow
-Wno-void-pointer-to-enum-cast -Wno-void-point
er-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source
-Werror=address-of-temporary -Werror=return-type
-Wno-tautological-constant-compare -Wno-tautological-type-limit-compare
-Wno-reorder-init-list -Wno-implicit-int-float-conversion
-Wno-int-in-bool-context -Wno-sizeof-arr
ay-div -Wno-tautological-overlap-compare -Wno-deprecated-copy
-Wno-range-loop-construct -Wno-misleading-indentation
-Wno-zero-as-null-pointer-constant
-Wno-deprecated-anon-enum-enum-conversion
-Wno-deprecated-enum-enum-conversion -Wno-string-compare
-Wno-enum-enum-conversion -Wno-e
num-float-conversion -Wno-pessimizing-move
-Wno-non-c-typedef-for-linkage -Wno-string-concatenation -MD -MF
out/soong/.intermediates/frameworks/native/libs/binder/libbinder/linux_glibc_x86_64_static/obj/frameworks/native/libs/binder/LazyServiceRegistrar.o.d
-o out/soong/.intermedia
tes/frameworks/native/libs/binder/libbinder/linux_glibc_x86_64_static/obj/frameworks/native/libs/binder/LazyServiceRegistrar.o
frameworks/native/libs/binder/LazyServiceRegistrar.cpp
In file included from
frameworks/native/libs/binder/LazyServiceRegistrar.cpp:20:
In file included from
frameworks/native/libs/binder/include/binder/LazyServiceRegistrar.h:21:
frameworks/native/libs/binder/include/binder/IServiceManager.h:106:11:
error: expected ';' at end of declaration list
    bool b GUARDED_BY(a);

Change-Id: I1d392b9efac1c6b7066c3231a810a25aecd02277